# Generated by Django 5.2.7 on 2025-11-28 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaldetection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='all_predictions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='antibiotics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='contagious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='severity',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='status',
            field=models.CharField(choices=[('diagnosed', 'Diagnosed'), ('treated', 'Treated'), ('recovered', 'Recovered'), ('pending', 'Pending')], default='diagnosed', max_length=20),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='symptoms',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='animaldetection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='animaldetection',
            index=models.Index(fields=['user', '-created_at'], name='animal_anim_user_id_602345_idx'),
        ),
        migrations.AddIndex(
            model_name='animaldetection',
            index=models.Index(fields=['disease_name'], name='animal_anim_disease_578560_idx'),
        ),
    ]
