# Generated by Django 5.2.7 on 2025-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_add_causes_duration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldetection',
            name='prevention',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='animaldetection',
            name='treatment',
            field=models.JSONField(default=list),
        ),
    ]
