# Generated by Django 5.2.7 on 2025-12-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_remove_causes_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_age', models.IntegerField(blank=True, null=True)),
                ('input_symptoms', models.JSONField(default=list)),
                ('disease_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_id', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('match_rate', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('matched_symptoms', models.JSONField(default=list)),
                ('treatment', models.JSONField(default=list)),
                ('prevention', models.JSONField(default=list)),
                ('medicines', models.JSONField(default=list)),
                ('contagious', models.BooleanField(default=False)),
                ('all_results', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('diagnosed', 'Diagnosed'), ('treated', 'Treated'), ('recovered', 'Recovered'), ('pending', 'Pending')], default='diagnosed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symptom Diagnosis',
                'verbose_name_plural': 'Symptom Diagnoses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='animal_symp_user_id_2745c9_idx'), models.Index(fields=['disease_name'], name='animal_symp_disease_4b21dc_idx'), models.Index(fields=['status'], name='animal_symp_status_991f20_idx')],
            },
        ),
    ]
